"""
Query enrichment module for user requests (EF4.1).
Automatically enriches short input sentences (< 5 words)
to improve NLP embedding precision.
Enrichment is generated by Gemini (GenAI), with a local rule-based fallback
used only if the API key is missing or the call fails.
"""
import json
import sys
from typing import Optional
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from src.services.gemini_service import call_gemini

# Configuration
WORD_THRESHOLD = 5  # Seuil minimum de mots

# Cache pour éviter les appels API répétés
CACHE_FILE = Path(__file__).parent / ".query_cache.json"
_CACHE = None

def load_cache():
    """Loads cache from file."""
    global _CACHE
    if _CACHE is None:
        if CACHE_FILE.exists():
            try:
                with open(CACHE_FILE, 'r', encoding='utf-8') as f:
                    _CACHE = json.load(f)
            except:
                _CACHE = {}
        else:
            _CACHE = {}
    return _CACHE

def save_cache():
    """Saves cache to file."""
    global _CACHE
    if _CACHE is not None:
        try:
            with open(CACHE_FILE, 'w', encoding='utf-8') as f:
                json.dump(_CACHE, f, ensure_ascii=False, indent=2)
        except Exception as e:
            print(f"Warning: could not save cache: {e}")

def is_query_too_short(query: str) -> bool:
    """
    Checks if a query is too short (< 5 words).
    
    Args:
        query: User query text
        
    Returns:
        True if query contains fewer than 5 words
        
    Example:
        >>> is_query_too_short("action movie")
        True
        >>> is_query_too_short("I want an intense action movie")
        False
    """
    if not query or not query.strip():
        return True
    return len(query.strip().split()) < WORD_THRESHOLD

def _local_fallback_expansion(query: str) -> str:
    """
    Minimal local fallback used only when Gemini is unavailable (no API key
    or a failed call), so the app keeps working without network access.
    """
    fallback_words = "movie intense engaging cinematic drama suspense"
    return f"{query} {fallback_words}"

def augment_query_with_gemini(query: str, api_key: Optional[str] = None, use_cache: bool = True) -> str:
    """
    Enriches a short query (< 5 words) using Gemini (EF4.1) to improve
    semantic embedding precision. Falls back to a local rule-based
    expansion if the API key is missing or the call fails.

    Args:
        query: Original user query
        api_key: Unused, kept for backward compatibility (key is read from env)
        use_cache: Use cache to avoid repeated API calls

    Returns:
        Enriched query (or original query if already long enough)
    """
    if not is_query_too_short(query):
        print(f"[OK] Query long enough ({len(query.split())} words), no enrichment needed")
        return query

    cache = load_cache()
    cache_key = query.lower().strip()

    print(f"\n[EF4.1] - Short query detected ({len(query.split())} words)")
    print(f"   [Input] : '{query}'")

    prompt = (
        "You enrich short movie-search queries for a semantic search engine (SBERT). "
        "Given the short user query below, produce a single enriched search phrase "
        "(15-20 words max, in English) that adds relevant cinematic keywords "
        "(genre, mood, tone, themes) while keeping the original intent. "
        "Reply with ONLY the enriched phrase, no explanation.\n\n"
        f"User query: \"{query}\""
    )

    augmented_query = call_gemini(
        prompt=prompt,
        namespace="query_augmentation",
        cache=cache if use_cache else None,
        cache_key=cache_key if use_cache else None,
        temperature=0.4,
        fallback_fn=lambda: _local_fallback_expansion(query),
    )

    # Safety net: never return an empty enrichment
    if not augmented_query.strip():
        augmented_query = _local_fallback_expansion(query)

    if use_cache:
        cache[cache_key] = augmented_query
        save_cache()

    print(f"   [Output] : '{augmented_query}'\n")
    return augmented_query

def augment_query_batch(queries: list[str], api_key: Optional[str] = None) -> list[str]:
    """
    Enriches multiple queries in batch (EF4.1).
    
    Args:
        queries: List of queries to enrich
        api_key: Not used (backward compatibility)
    
    Returns:
        List of enriched queries
    """
    return [augment_query_with_gemini(q, api_key) for q in queries]

